services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:16.1.1
    volumes:
      - ./realms/:/realms/
      - ./scripts/:/opt/jboss/startup-scripts/
      - ./jar/:/opt/jboss/keycloak/standalone/deployments/
    env_file: .env
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.provider=custom"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.dir=/realms/"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Djboss.as.management.blocking.timeout=3600"
    ports:
      - 8080:8080