services:
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:24.0.3
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./realms/:/realms/
      - ./jar/:/opt/bitnami/keycloak/providers/
    environment:
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_DATABASE_NAME: test
      KEYCLOAK_DATABASE_HOST: host.docker.internal
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.migration.provider=custom
                            -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
                            -Dkeycloak.migration.action=import
                            -Dkeycloak.migration.dir=/realms"
    ports:
      - 8080:8080